package crypto

import (
	"context"
	"encoding/base64"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
)

// GetPrivateKey scans all trusted_keys rows and returns the first RSA private-key PEM
// that can be decrypted with the encoded form of userPassword. Returns "" if none match.
func GetPrivateKey(ctx context.Context, pool *pgxpool.Pool, userPassword, pepper string) (string, error) {
	rows, err := pool.Query(ctx, `SELECT key FROM trusted_keys`)
	if err != nil {
		return "", fmt.Errorf("query trusted_keys: %w", err)
	}
	defer rows.Close()
	encoded := EncodedPassword(userPassword, pepper)
	for rows.Next() {
		var encryptedKey string
		if err := rows.Scan(&encryptedKey); err != nil {
			return "", err
		}
		plain, err := Decrypt(encryptedKey, encoded, pepper)
		if err != nil {
			continue
		}
		return plain, nil
	}
	return "", rows.Err()
}

// GetTrustedKeyID returns the DB id of the trusted_key row that can be decrypted
// with userPassword. Returns -1 and an error if none match.
func GetTrustedKeyID(ctx context.Context, pool *pgxpool.Pool, userPassword, pepper string) (int, error) {
	rows, err := pool.Query(ctx, `SELECT key, id FROM trusted_keys`)
	if err != nil {
		return -1, fmt.Errorf("query trusted_keys: %w", err)
	}
	defer rows.Close()
	encoded := EncodedPassword(userPassword, pepper)
	for rows.Next() {
		var encKey string
		var id int
		if err := rows.Scan(&encKey, &id); err != nil {
			return -1, err
		}
		if _, err := Decrypt(encKey, encoded, pepper); err == nil {
			return id, nil
		}
	}
	if err := rows.Err(); err != nil {
		return -1, err
	}
	return -1, fmt.Errorf("no trusted key found for supplied password")
}

// CheckMasterPassword returns true if the master-flagged trusted key can be decrypted
// with password.
func CheckMasterPassword(ctx context.Context, pool *pgxpool.Pool, password, pepper string) (bool, error) {
	rows, err := pool.Query(ctx, `SELECT key FROM trusted_keys WHERE is_master = TRUE`)
	if err != nil {
		return false, fmt.Errorf("query trusted_keys: %w", err)
	}
	defer rows.Close()
	encoded := EncodedPassword(password, pepper)
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return false, err
		}
		if _, err := Decrypt(key, encoded, pepper); err == nil {
			return true, nil
		}
	}
	return false, rows.Err()
}

// GetMasterPublicKey reads the encrypted public key from master_keys and decrypts it
// with masterPassword. Returns the PEM string.
func GetMasterPublicKey(ctx context.Context, pool *pgxpool.Pool, masterPassword, pepper string) (string, error) {
	var encPublic string
	err := pool.QueryRow(ctx, `SELECT public_key FROM master_keys LIMIT 1`).Scan(&encPublic)
	if err != nil {
		return "", fmt.Errorf("read master_keys: %w", err)
	}
	pub, err := Decrypt(encPublic, masterPassword, pepper)
	if err != nil {
		return "", fmt.Errorf("decrypt public key: %w", err)
	}
	return pub, nil
}

// GenerateMasterKey creates a new RSA 2048-bit key pair, stores the encrypted public key
// in master_keys (clearing any previous records), and inserts a trusted key for masterPassword.
func GenerateMasterKey(ctx context.Context, pool *pgxpool.Pool, masterPassword, pepper string) error {
	privPEM, pubPEM, err := GenerateRSAKeyPair()
	if err != nil {
		return fmt.Errorf("generate RSA key pair: %w", err)
	}
	encPublic, err := Encrypt(pubPEM, masterPassword, pepper)
	if err != nil {
		return fmt.Errorf("encrypt public key: %w", err)
	}
	// Clear existing keys and data.
	for _, stmt := range []string{
		`TRUNCATE TABLE master_keys`,
		`TRUNCATE TABLE trusted_keys`,
		`TRUNCATE TABLE sensitive_data`,
	} {
		if _, err := pool.Exec(ctx, stmt); err != nil {
			return fmt.Errorf("truncate: %w", err)
		}
	}
	if _, err := pool.Exec(ctx,
		`INSERT INTO master_keys (comment, public_key) VALUES ($1, $2)`,
		"Generated by digitalmuseum", encPublic,
	); err != nil {
		return fmt.Errorf("insert master_keys: %w", err)
	}
	// Insert trusted key for the master password (with the private key as the payload).
	return insertTrustedKey(ctx, pool, privPEM, masterPassword, true, pepper)
}

// GenerateTrustedKey inserts a new trusted_keys row for userPassword using the master
// private key retrieved with masterPassword.
func GenerateTrustedKey(ctx context.Context, pool *pgxpool.Pool, userPassword, masterPassword, pepper string) error {
	privPEM, err := GetPrivateKey(ctx, pool, masterPassword, pepper)
	if err != nil {
		return fmt.Errorf("get master private key: %w", err)
	}
	if privPEM == "" {
		return fmt.Errorf("master private key not found — check master password")
	}
	isMaster := userPassword == masterPassword
	return insertTrustedKey(ctx, pool, privPEM, userPassword, isMaster, pepper)
}

// DeleteTrustedKey removes a user's trusted key. Requires a valid master password and
// refuses to delete the master key.
func DeleteTrustedKey(ctx context.Context, pool *pgxpool.Pool, userPassword, masterPassword, pepper string) error {
	if userPassword == masterPassword {
		return fmt.Errorf("cannot delete master key")
	}
	ok, err := CheckMasterPassword(ctx, pool, masterPassword, pepper)
	if err != nil {
		return fmt.Errorf("check master password: %w", err)
	}
	if !ok {
		return fmt.Errorf("invalid master password")
	}
	id, err := GetTrustedKeyID(ctx, pool, userPassword, pepper)
	if err != nil {
		return err
	}
	_, err = pool.Exec(ctx, `DELETE FROM trusted_keys WHERE id = $1`, id)
	return err
}

// EncryptRecord encrypts details with the master public key and returns a base64 string
// suitable for storage in the sensitive_data.details column.
func EncryptRecord(ctx context.Context, pool *pgxpool.Pool, masterPassword, details, pepper string) (string, error) {
	pubPEM, err := GetMasterPublicKey(ctx, pool, masterPassword, pepper)
	if err != nil {
		return "", err
	}
	encrypted, err := EncryptWithPublicKeyHybrid([]byte(pubPEM), []byte(details))
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(encrypted), nil
}

// DecryptRecord decrypts a base64-encoded record detail using the private key for password.
func DecryptRecord(privateKeyPEM, encryptedB64 string) (string, error) {
	data, err := base64.StdEncoding.DecodeString(encryptedB64)
	if err != nil {
		return "", fmt.Errorf("base64 decode: %w", err)
	}
	plain, err := DecryptWithPrivateKeyHybrid([]byte(privateKeyPEM), data)
	if err != nil {
		return "", err
	}
	return string(plain), nil
}

func insertTrustedKey(ctx context.Context, pool *pgxpool.Pool, privPEM, password string, isMaster bool, pepper string) error {
	encoded := EncodedPassword(password, pepper)
	encKey, err := Encrypt(privPEM, encoded, pepper)
	if err != nil {
		return fmt.Errorf("encrypt trusted key: %w", err)
	}
	_, err = pool.Exec(ctx,
		`INSERT INTO trusted_keys (key, is_master) VALUES ($1, $2)`,
		encKey, isMaster,
	)
	return err
}
